# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.0
  - 1
  - nightly

matrix:
  allow_failures:
  - julia: nightly

addons:
  apt:
    packages:
      - at-spi2-core
      - libgtk-3-dev
      - xauth
      - xvfb

env:
  - GKS_ENCODING="utf8"

cache:
  directories:
  - $HOME/.julia/artifacts

sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pwd ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/install_wkhtmltoimage.sh ; fi

notifications:
  email: true

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD -e 'using Pkg; pkg"add https://github.com/JuliaPlots/RecipesPipeline.jl"; Pkg.build(); Pkg.test(coverage=true)'
