# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  #- nightly
notifications:
  email: true
# uncomment the following lines to override the default test script
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd()); Pkg.build("Plots")'
 # - julia -e 'Pkg.clone("https://github.com/tbreloff/Images.jl.git"); Pkg.checkout("Images","tom_imgcompare");'
 # - julia -e 'Pkg.clone("Images"); Pkg.build("Images")'
 # - julia -e 'Pkg.clone("ImageMagick"); Pkg.build("ImageMagick")'
 - julia -e 'Pkg.clone("https://github.com/tbreloff/ImageMagick.jl.git"); Pkg.checkout("ImageMagick","tb_write"); Pkg.build("ImageMagick")'
 - julia -e 'Pkg.clone("https://github.com/tbreloff/VisualRegressionTests.jl.git");'
 - julia -e 'Pkg.clone("https://github.com/tbreloff/ExamplePlots.jl.git");'
 - julia -e 'Pkg.checkout("Blink"); Pkg.build("Blink"); import Blink; Blink.AtomShell.install()'
 - julia -e 'Pkg.checkout("PlotlyJS")'
 # - julia -e 'Pkg.add("Cairo"); Pkg.build("Cairo")'
 - julia -e 'ENV["PYTHON"] = ""; Pkg.add("PyPlot"); Pkg.build("PyPlot")'
 - julia -e 'Pkg.test("Plots"; coverage=false)'
 # - julia -e 'cd(Pkg.dir("Plots")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
