name: CI
on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
    tags:
      - "*"
defaults:
  run:
    shell: bash
env:
  JULIA_NUM_THREADS: auto
jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        julia-version:
          - "1.6"
          - "1"
          - "nightly"
        exclude:
          - os: windows-latest
            julia-version: "1.6"
          - os: macos-latest
            julia-version: "1.6"
        include:
          - os: ubuntu-latest
            julia-prefix: xvfb-run
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v2
        with:
          show-versioninfo: true
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1
        with:
          ignore-no-cache: true
          localregistry: https://github.com/0h7z/0hjl.git
      - uses: julia-actions/julia-runtest@v1
        with:
          prefix: ${{ matrix.julia-prefix }}
      - uses: heptazhou/julia-codecov@v1
      - uses: codecov/codecov-action@v3.1.5
        with:
          file: lcov.info
